version: '3.9'

services:
  elasticsearch:
    container_name: elastic_compose
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      ELASTIC_USERNAME: ${ELASTIC_USER}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - elk

  kibana:
    container_name: kibana_compose
    image: docker.elastic.co/kibana/kibana:8.1.3
    ports:
      - 5601:5601
    networks:
      - elk
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash_compose
    image: docker.elastic.co/logstash/logstash:8.1.3
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - ${PWD}/logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elk
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      output.elasticsearch.user: ${ELASTIC_USER}
      output.elasticsearch.password: ${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch

  filebeat:
    container_name: filebeat_compose
    entrypoint: sh /etc/entrypoint/setup.sh
    build:
      context: ./filebeat
    volumes:
      - logs:/var/log/server
    networks:
      - elk
    depends_on:
      - logstash

  app:
    build: .
    container_name: app_compose
    volumes:
      - logs:/usr/app/logs
    ports:
      - 3334:3334
    networks:
      - elk
    depends_on:
      - filebeat

volumes:
  logs:

networks:
  elk:
